### PR TITLE
Updated CreateNewPlan page.

### PR DESCRIPTION
**Pull request by akcgjc007**
## Updated CreateNewPlan page

- Improved borders
- Auto constraint check

Screenshot from 2021-07-17 14-50-52

### CODE REVIEW

**Comment by kshru9** [comment]
The drop down hides when card is hovered?
image

**Comment by akcgjc007** [comment]
We can just remove the hover then.

**Comment by kshru9** [comment]
> We can just remove the hover then.

Great.

**Review by kshru9 — APPROVED** [review]
Awesome @akcgjc007

**Pull request merged**
